# Generated by Django 3.0.2 on 2020-02-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0004_auto_20200206_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
