# Generated by Django 3.0.2 on 2020-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0005_auto_20200213_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('Sc', 'Science'), ('health', 'Health'), ('food', 'Food'), ('Tech', 'Technology'), ('writing', 'Writing'), ('music', 'Music'), ('movie', 'Movies')], max_length=200),
        ),
    ]
