# Generated by Django 3.0.2 on 2020-02-17 09:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0007_auto_20200217_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sc', 'Science'), ('health', 'Health'), ('food', 'Food'), ('Tech', 'Technology'), ('writing', 'Writing'), ('music', 'Music'), ('movie', 'Movies'), ('life', 'Life')], max_length=44),
        ),
    ]
