# Generated by Django 3.0.2 on 2020-02-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0008_auto_20200217_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
