# Generated by Django 3.0.2 on 2020-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0009_auto_20200218_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(to='quora_app.Topic'),
        ),
    ]
