# Generated by Django 3.0.2 on 2020-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0012_auto_20200219_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
